<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Restaurant;
use App\Models\RestaurantStock;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'restaurant_id' => 'R0001',
                'name' => 'Dunkin\' Donuts',
                'location' => 'Mal Artha Gading, Jl. Artha Gading Sel. No.1, Jakarta Utara',
                'operational_hours' => '07:00 - 22:00',
                'description' => 'Donat dan kopi pilihan terbaik.',
                'food_type' => 'Bakery & Coffee',
                'applicant_name' => 'John Doe',
                'telephone' => '08121234567',
                'account_bank' => 'BCA',
                'bank_account_name' => 'Dunkin\' Donuts',
                'pricing_tier' => 40000,
                'ratings_count' => 55,
                'avg_rating' => 4.6,
                'best_before' => now()->addDays(2)->toDateString(),
                'restaurant_picture_path' => 'restaurants/dunkin.jpeg',
                'product_sold_picture_path' => 'products/dunkin_donut.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'dunkin@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0002',
                'name' => 'J.CO Donuts & Coffee',
                'location' => 'Trans Studio Mall, Jl. Gatot Subroto No.289, Bandung',
                'operational_hours' => '08:00 - 21:00',
                'description' => 'Donat premium dengan topping unik dan kopi Italia.',
                'food_type' => 'Bakery & Coffee',
                'applicant_name' => 'Jane Smith',
                'telephone' => '08129876543',
                'account_bank' => 'Mandiri',
                'bank_account_name' => 'J.CO Donuts & Coffee',
                'pricing_tier' => 45000,
                'ratings_count' => 78,
                'avg_rating' => 4.7,
                'best_before' => now()->addDays(3)->toDateString(),
                'restaurant_picture_path' => 'restaurants/jco.jpeg',
                'product_sold_picture_path' => 'products/jco_donuts.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'jco@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0003',
                'name' => 'Krispy Kreme',
                'location' => 'Pakuwon Mall, Jl. Mayjen Yono Suwoyo No.2, Surabaya',
                'operational_hours' => '09:00 - 20:00',
                'description' => 'Donat hangat yang lumer di mulut.',
                'food_type' => 'Bakery',
                'applicant_name' => 'Peter Jones',
                'telephone' => '08561234567',
                'account_bank' => 'BNI',
                'bank_account_name' => 'Krispy Kreme',
                'pricing_tier' => 38000,
                'ratings_count' => 42,
                'avg_rating' => 4.4,
                'best_before' => now()->addDays(1)->toDateString(),
                'restaurant_picture_path' => 'restaurants/krispykreme.jpeg',
                'product_sold_picture_path' => 'products/krispykreme_original.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'krispykreme@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0004',
                'name' => 'Pizza Hut',
                'location' => 'Malioboro Mall, Jl. Malioboro No.52-58, Yogyakarta',
                'operational_hours' => '10:00 - 23:00',
                'description' => 'Pilihan pizza beragam dengan bahan-bahan segar.',
                'food_type' => 'Pizza & Italian',
                'applicant_name' => 'Laura Miller',
                'telephone' => '08213456789',
                'account_bank' => 'BRI',
                'bank_account_name' => 'Pizza Hut',
                'pricing_tier' => 75000,
                'ratings_count' => 90,
                'avg_rating' => 4.8,
                'best_before' => now()->addDays(1)->toDateString(),
                'restaurant_picture_path' => 'restaurants/pizzahut.jpeg',
                'product_sold_picture_path' => 'products/pizzahut_pizza.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'pizzahut@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0005',
                'name' => 'Starbucks',
                'location' => 'Centre Point Mall, Jl. Jawa No.8, Medan',
                'operational_hours' => '06:00 - 23:00',
                'description' => 'Kopi premium dan kue-kue lezat.',
                'food_type' => 'Coffee & Bakery',
                'applicant_name' => 'David Lee',
                'telephone' => '08781122334',
                'account_bank' => 'BCA',
                'bank_account_name' => 'Starbucks',
                'pricing_tier' => 60000,
                'ratings_count' => 65,
                'avg_rating' => 4.9,
                'best_before' => now()->addDays(1)->toDateString(),
                'restaurant_picture_path' => 'restaurants/starbucks.jpeg',
                'product_sold_picture_path' => 'products/starbucks_cake.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'starbucks@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0006',
                'name' => 'Chatime',
                'location' => 'Mall Ratu Indah, Jl. DR. Sam Ratulangi No.35, Makassar',
                'operational_hours' => '10:00 - 22:00',
                'description' => 'Minuman teh susu dengan beragam topping.',
                'food_type' => 'Beverages',
                'applicant_name' => 'Sophia Chen',
                'telephone' => '08123344556',
                'account_bank' => 'Mandiri',
                'bank_account_name' => 'Chatime',
                'pricing_tier' => 25000,
                'ratings_count' => 30,
                'avg_rating' => 4.1,
                'best_before' => now()->addDays(0)->toDateString(),
                'restaurant_picture_path' => 'restaurants/chatime.jpeg',
                'product_sold_picture_path' => 'products/chatime_drink.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'chatime@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0007',
                'name' => 'Warung Nasi Uduk Betawi',
                'location' => 'Jl. Kebon Kacang Raya No.45, Jakarta Pusat',
                'operational_hours' => '17:00 - 01:00',
                'description' => 'Nasi uduk otentik dengan lauk lengkap.',
                'food_type' => 'Indonesian',
                'applicant_name' => 'Ahmad Subroto',
                'telephone' => '08126677889',
                'account_bank' => 'BCA',
                'bank_account_name' => 'Warung Nasi Uduk',
                'pricing_tier' => 22000,
                'ratings_count' => 8,
                'avg_rating' => 4.3,
                'best_before' => now()->addDays(1)->toDateString(),
                'restaurant_picture_path' => 'restaurants/nasiuduk.jpeg',
                'product_sold_picture_path' => 'products/nasiuduk_meal.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'nasiuduk@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted', 
            ],
            [
                'restaurant_id' => 'R0008',
                'name' => 'Solaria',
                'location' => 'Paris Van Java Mall, Jl. Sukajadi No.137-139, Bandung',
                'operational_hours' => '10:00 - 22:00',
                'description' => 'Hidangan rumahan dengan cita rasa spesial.',
                'food_type' => 'Asian & Fusion',
                'applicant_name' => 'Lisa Handayani',
                'telephone' => '08127788990',
                'account_bank' => 'BNI',
                'bank_account_name' => 'Solaria',
                'pricing_tier' => 40000,
                'ratings_count' => 25,
                'avg_rating' => 4.2,
                'best_before' => now()->addDays(2)->toDateString(),
                'restaurant_picture_path' => 'restaurants/solaria.jpeg',
                'product_sold_picture_path' => 'products/solaria_mie.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'solaria@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0009',
                'name' => 'Ayam Bakar Taliwang',
                'location' => 'Jl. Raya Senggigi No.12, Lombok Barat, NTB',
                'operational_hours' => '11:00 - 21:00',
                'description' => 'Spesialis ayam bakar khas Lombok yang pedas dan lezat.',
                'food_type' => 'Indonesian',
                'applicant_name' => 'Farhan Aditama',
                'telephone' => '08129988776',
                'account_bank' => 'BRI',
                'bank_account_name' => 'Ayam Bakar Taliwang',
                'pricing_tier' => 35000,
                'ratings_count' => 15,
                'avg_rating' => 4.6,
                'best_before' => now()->addDays(1)->toDateString(),
                'restaurant_picture_path' => 'restaurants/ayambakar.jpeg',
                'product_sold_picture_path' => 'products/ayambakar_meal.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'taliwang@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
            [
                'restaurant_id' => 'R0010',
                'name' => 'Bakmi GM',
                'location' => 'Grand Indonesia Shopping Town, Jl. M.H. Thamrin No.1, Jakarta Pusat',
                'operational_hours' => '09:00 - 22:00',
                'description' => 'Bakmi legendaris dengan resep turun-temurun.',
                'food_type' => 'Noodle',
                'applicant_name' => 'Jessica Wong',
                'telephone' => '08125544332',
                'account_bank' => 'Mandiri',
                'bank_account_name' => 'Bakmi GM',
                'pricing_tier' => 42000,
                'ratings_count' => 60,
                'avg_rating' => 4.5,
                'best_before' => now()->addDays(2)->toDateString(),
                'restaurant_picture_path' => 'restaurants/bakmigm.jpeg',
                'product_sold_picture_path' => 'products/bakmigm_bakmi.jpeg',
                'id_proof_document_path' => null,
                'npwp_document_path' => null,
                'authorization_document_path' => null,
                'email' => 'bakmigm@example.com',
                'password' => Hash::make('12345678'),
                'status' => 'accepted',
            ],
        ];

        foreach ($restaurants as $data) {
            $restaurant = Restaurant::create($data);

            // Menambahkan stok untuk setiap restoran
            RestaurantStock::create([
                'restaurant_id' => $restaurant->restaurant_id,
                'item_name' => $restaurant->name,
                'pickup_time' => 'Lunch',
                'stock' => 10,
                'start_time' => '12:00:00',
                'end_time' => '13:00:00',
            ]);
            
            RestaurantStock::create([
                'restaurant_id' => $restaurant->restaurant_id,
                'item_name' => $restaurant->name,
                'pickup_time' => 'Dinner',
                'stock' => 15,
                'start_time' => '18:00:00',
                'end_time' => '19:00:00',
            ]);
        }
    }
}